import{s as p,i as c}from"./assets/vendor-8ce50246.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();function f(o){const e="42321228-2dc7965d40466a0a646776a28",s="https://pixabay.com",a="/api/",t=`?key=${e}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=s+a+t;return fetch(r).then(i=>i.json())}let l;const n={form:document.querySelector(".form"),input:document.querySelector(".input-search"),button:document.querySelector(".button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function m(o){return o.map(e=>`
        <li class="gallery-item"><a href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
        <div class="info">
        <p><span class="info-text">Likes</span>${e.likes}</p>
        <p><span class="info-text">Views</span>${e.views}</p>
        <p><span class="info-text">Comments</span>${e.comments}</p>
        <p><span class="info-text">Downloads</span>${e.downloads}</p>
        </div>
        </li>
        `).join("")}function y(o){const e=m(o);n.gallery.innerHTML=e,typeof l<"u"?l.refresh():l=new p(".gallery a",{captionsData:"alt",captionsDelay:250})}n.loader.style.display="none";n.form.addEventListener("submit",d);function d(o){if(u(),o.preventDefault(),n.input.value.trim()===""||n.input.value.trim().length===0)return;n.gallery.innerHTML="",n.loader.style.display="block";const e=o.target.elements.search.value;f(e).then(s=>{s.hits.lenght===0?(u(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInLeft"})):y(s.hits)}).catch(s=>{c.error({message:s.message||"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInLeft"})}).finally(()=>{n.loader.style.display="none"}),o.target.reset()}function u(){n.gallery.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
